name: Build

on:
  pull_request:
    branches:
      develop
    types:
      - closed

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  build-job:
    name: Docker image build
    runs-on: ubuntu-latest

    # check the PR was actually merged, not simply closed
    if: |
      github.event.pull_request.merged == true

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build, tag and push image
        id: build-image
        run: |
          export GIT_HASH=$(git rev-parse --short HEAD)
          echo ./build.sh   ${{env.ECR_REGISTRY}}/${{env.ECR_REPO}} ${GIT_HASH}
          echo ./publish.sh ${{env.ECR_REGISTRY}}/${{env.ECR_REPO}} ${GIT_HASH}

          ./build.sh
          ./publish.sh ${{env.ECR_REGISTRY}}/${{env.ECR_REPO}}:${GIT_HASH}
        env:
          AWS_REGION:       ${{ vars.AWS_REGION }}
          ECR_REGISTRY:     ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO:         hello-world

  # ---------------------------------------------
  #              Deploy
  # ---------------------------------------------
  deploy-job:
    name: Deploy on Dev
    needs: build-job

    secrets: inherit
    uses: ./.github/workflows/common-deploy.yml
    with:
      stage_name: dev
      
