# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the "develop" branch.
#
name: Deployment
on:
  workflow_call:
    inputs:
      stage_name:
        description: The stage name, i.e. 'dev', 'prod', 'staging'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{inputs.stage_name}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      #with:
      #  fetch-depth: 0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    #- name: Debug branches and variables
    #  run: |
    #    # target (in a pR)
    #    echo "GITHUB_BASE_REF (target) = $GITHUB_BASE_REF"
    #
    #    # source (in a PR)
    #    echo "GITHUB_HEAD_REF (source) = $GITHUB_HEAD_REF"
    #
    #    echo "show branches"
    #    git branch -a

    - name: Determine TAG to deploy
      run: |
        echo "🔷 git fetch --tags --force"
        git fetch --tags --force
        echo "🔷 git tag"
        git tag

        echo "🔷 git fetch --tags origin"
        git fetch --tags origin
        echo "🔷 git tag"
        git tag

        echo "🔷 git fetch --tags origin --force"
        git fetch --tags origin --force
        echo "🔷 git tag"
        git tag


        echo "🟣 GITHUB_BASE_REF=$GITHUB_BASE_REF"
        echo "🟣 git tag --merged $GITHUB_BASE_REF"
        git tag --merged $GITHUB_BASE_REF

        echo "🟣 TAG=$( git tag --merged $GITHUB_BASE_REF | tail -n 1 )"
        TAG=$( git tag --merged $GITHUB_BASE_REF | tail -n 1 )

        echo "🟣 TAG=$TAG"
