name: Deploy Prod

on:
  pull_request:
    branches:
      master
    types:
      - closed

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  # ---------------------------------------------
  #              Deploy
  # ---------------------------------------------
  deploy-job:
    name: Deploy on Prod

    secrets: inherit
    uses: ./.github/workflows/common-deploy.yml
    with:
      stage_name: prod
      
