name: Deploy Staging

on:
  pull_request:
    branches:
      staging
    types:
      - closed

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  # ---------------------------------------------
  #              Deploy
  # ---------------------------------------------
  deploy-job:
    name: Deploy on Staging

    secrets: inherit
    uses: ./.github/workflows/common-deploy.yml
    with:
      stage_name: staging
      
